import os
import resend
import json
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Configure Resend API Key
resend.api_key = os.getenv("RESEND_API_KEY")

def send_alert_email(payload: dict, to_email: str = "trinayan.mahato1303@gmail.com"):
    """
    Sends an email alert using Resend.
    """
    email_params = {
        "from": "onboarding@resend.dev",
        "to": [to_email],
        "subject": "SIEM Alert Triggered by Elastalert!",
        "html": f"<h3>New SIEM Alert</h3><p>An alert was triggered with the following details:</p><pre>{json.dumps(payload, indent=2)}</pre>"
    }
    email_response = resend.Emails.send(email_params)
    return email_response


def send_permanent_block_approval_email(
    ip_address: str,
    alert_id: int,
    reasoning: str,
    api_base_url: str = "http://127.0.0.1:8000",
    to_email: str = "trinayan.mahato1303@gmail.com"
):
    """
    Sends a human-in-the-loop approval email for a permanent IP block.
    Contains two clickable buttons: one to block, one to dismiss.
    """
    block_url    = f"{api_base_url}/action/block-permanently?alert_id={alert_id}&ip={ip_address}"
    dismiss_url  = f"{api_base_url}/action/no-action?alert_id={alert_id}&ip={ip_address}"

    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
        <h2 style="color: #c0392b;">⚠️ SIEM — Permanent Block Approval Required</h2>
        <p>The AI analyst has reviewed recent SSH logs for the following IP and is recommending a <strong>permanent block</strong>.</p>

        <table style="width:100%; border-collapse: collapse; margin-bottom: 16px;">
            <tr>
                <td style="padding: 8px; font-weight: bold; background: #f5f5f5; border: 1px solid #ddd;">IP Address</td>
                <td style="padding: 8px; border: 1px solid #ddd;"><code>{ip_address}</code></td>
            </tr>
            <tr>
                <td style="padding: 8px; font-weight: bold; background: #f5f5f5; border: 1px solid #ddd;">Alert ID</td>
                <td style="padding: 8px; border: 1px solid #ddd;">#{alert_id}</td>
            </tr>
        </table>

        <h3 style="color: #555;">AI Reasoning:</h3>
        <blockquote style="border-left: 4px solid #c0392b; margin: 0; padding: 12px 16px; background: #fff5f5; color: #333;">
            {reasoning}
        </blockquote>

        <p style="margin-top: 24px;">Please review and choose an action:</p>

        <div style="display: flex; gap: 16px; margin-top: 8px;">
            <a href="{block_url}"
               style="display:inline-block; padding: 12px 24px; background-color: #c0392b; color: white;
                      text-decoration: none; border-radius: 6px; font-weight: bold;">
                🚫 Block Permanently
            </a>
            &nbsp;&nbsp;
            <a href="{dismiss_url}"
               style="display:inline-block; padding: 12px 24px; background-color: #27ae60; color: white;
                      text-decoration: none; border-radius: 6px; font-weight: bold;">
                ✅ No Action (Dismiss)
            </a>
        </div>

        <p style="margin-top: 24px; color: #888; font-size: 12px;">
            This email was automatically generated by your SIEM system. Manual review is required before a permanent block is applied.
        </p>
    </div>
    """

    email_params = {
        "from": "onboarding@resend.dev",
        "to": [to_email],
        "subject": f"[ACTION REQUIRED] Permanent Block Approval for IP: {ip_address}",
        "html": html
    }
    email_response = resend.Emails.send(email_params)
    return email_response


def send_users_block_approval_email(
    usernames: list,
    host_name: str,
    alert_id: int,
    reasoning: str,
    api_base_url: str = "http://127.0.0.1:8000",
    to_email: str = "trinayan.mahato1303@gmail.com"
):
    """
    Human-in-the-loop email for a multi-account attack on a workstation.
    'Yes' locks ALL listed users for 1 hour; 'No' dismisses.
    """
    from urllib.parse import quote
    users_param = quote(",".join(usernames))
    block_url = f"{api_base_url}/action/users-decision?alert_id={alert_id}&users={users_param}&decision=yes"
    dismiss_url = f"{api_base_url}/action/users-decision?alert_id={alert_id}&users={users_param}&decision=no"
    users_html = ", ".join(f"<code>{u}</code>" for u in usernames)

    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
        <h2 style="color: #c0392b;">⚠️ SIEM — Multi-Account Login Attack</h2>
        <p>Failed physical logins were detected against <strong>many accounts</strong> on <code>{host_name}</code>.
        This may be a brute-force / DDoS-style attack.</p>
        <p><strong>Accounts involved:</strong> {users_html}</p>
        <p><strong>Alert ID:</strong> #{alert_id}</p>
        <h3 style="color: #555;">AI Reasoning:</h3>
        <blockquote style="border-left: 4px solid #c0392b; margin: 0; padding: 12px 16px; background: #fff5f5; color: #333;">
            {reasoning}
        </blockquote>
        <p style="margin-top: 24px;">Lock all these accounts for 1 hour?</p>
        <a href="{block_url}" style="display:inline-block; padding: 12px 24px; background-color: #c0392b; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">
            🚫 Yes, Block All Users (1 hour)
        </a>
        &nbsp;&nbsp;
        <a href="{dismiss_url}" style="display:inline-block; padding: 12px 24px; background-color: #27ae60; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">
            ✅ No, Dismiss
        </a>
    </div>
    """

    return resend.Emails.send({
        "from": "onboarding@resend.dev",
        "to": [to_email],
        "subject": f"[ACTION REQUIRED] Multi-account login attack on {host_name}",
        "html": html
    })


def send_ip_decision_email(
    ip_address: str,
    host_name: str,
    alert_id: int,
    reasoning: str,
    api_base_url: str = "http://127.0.0.1:8000",
    to_email: str = "trinayan.mahato1303@gmail.com",
    title: str = "Privilege Escalation Attack",
    description: "str | None" = None
):
    """
    Approval email for a permanent IP block after repeated privilege escalation failures.
    `title`/`description` can be overridden so other handlers (e.g. HTTP 4xx) reuse this email + API.
    Both buttons hit the single /action/ip-decision endpoint.
    """
    base = f"{api_base_url}/action/ip-decision?alert_id={alert_id}&ip={ip_address}"
    if description is None:
        description = (
            f"Repeated failed <strong>sudo</strong> attempts were detected on <code>{host_name}</code>\n"
            f"        from IP <code>{ip_address}</code>."
        )
    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
        <h2 style="color: #c0392b;">⚠️ SIEM — {title}</h2>
        <p>{description} The AI recommends a <strong>permanent block</strong>.</p>
        <p><strong>Alert ID:</strong> #{alert_id}</p>
        <h3 style="color: #555;">AI Reasoning:</h3>
        <blockquote style="border-left: 4px solid #c0392b; margin: 0; padding: 12px 16px; background: #fff5f5; color: #333;">{reasoning}</blockquote>
        <p style="margin-top: 24px;">Block this IP and its access?</p>
        <a href="{base}&decision=yes" style="display:inline-block; padding: 12px 24px; background-color: #c0392b; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">🚫 Yes, Block IP</a>
        &nbsp;&nbsp;
        <a href="{base}&decision=no" style="display:inline-block; padding: 12px 24px; background-color: #27ae60; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">✅ No, Dismiss</a>
    </div>
    """
    return resend.Emails.send({
        "from": "onboarding@resend.dev",
        "to": [to_email],
        "subject": f"[ACTION REQUIRED] {title} from {ip_address}",
        "html": html
    })
